# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

title: Pragmatic Testing
description: Ignite-style lightning talks on the subject of pragmatism in software testing.
tagline: lightning talks on the topic of pragmatic testing
author :
  name : Nick MacInnis
  email : macinnis.nick@gmail.com
  github : nmacinnis

production_url : https://nmacinnis.github.io/pragmatic_testing

gems: ["jekyll-sitemap"]

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0

  BASE_PATH : https://nmacinnis.github.io/pragmatic_testing

  ASSET_PATH : false

  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change them here if needed.
  #
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : false

  analytics :
    provider : false

  sharing :
    provider : false

google_analytics: 
show_downloads: true
theme: jekyll-theme-slate